### ISSUE TITLE
raspberry_pi_read_esp32.py Problem

### ISSUE THREAD

**Issue by DexterBurns** [MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE#2]
Not sure, but i think the read_from_rpi_to_esp32 function in that example doesn't tell the esp32 that it is requesting data to be sent back to the pi. I believe it is just reading the empty (or junk) i2c buffer. What i think is missing is something to tell the esp32 so that it knows to activate the WireSlave.onRequest function when it receives the "i'm requesting data" signal from the pi. I came to this conclusion after testing the examples and fixing some typos i found in them. This example doesn't work as far as i know. I could be wrong though. Curious as to how this can be solved.

Thanks,

**Comment by MkLHX** [comment]
Hi @DexterBurns  could you please share your modified example snippet?
Il can take a look on it tomorrow. I developed and used this library inside a professional project and decide to share code after. So maybe the project inside and this repository are different...
Inside the professional project everything works well as expected.

**Comment by DexterBurns** [comment]
Didnt do too much changing of the example code, just switched around the slave_address variables and the register variables. The write_from_rpi_to_esp32() works fine for me. Alot of comments added where my concerns were. First block of code is what im running on my Pi3b+ and the next block is what i'm running on the esp32. The receiveEvent() function on the esp32 works with the write_from_rpi_to_esp32(). 


`from Adafruit_PureIO.smbus import SMBus  # pip install adafruit-blinka
from Raspberry_Pi_Master_for_ESP32_I2C_SLAVE.packer import Packer
from Raspberry_Pi_Master_for_ESP32_I2C_SLAVE.unpacker import Unpacker
import time

slave_address = 0x08  # slave address is 4
register = 0x25  # register to write is 0x01
value = 0x00

def write_from_rpi_to_esp32():
    try:
        # prepare the data
        packed = None
        with Packer() as packer:
            packer.write(register)
            packer.write(value)
            packer.end()
            packed = packer.read()
        # change 1 of SMBus(1) to bus number on your RPI
        with SMBus(1) as smbus:
            smbus.write_bytes(slave_address, bytearray(packed))
    except Exception as e:
        print("ERROR: {}".format(e))
        
def read_from_rpi_to_esp32():
    try:
        # prepare the data
        packed = None
        with Packer() as packer:
            packer.write(value)
            packer.end()
            packed = packer.read()
            print("in packer")

        # change 1 of SMBus(1) to bus number on your RPI
        raw_list = None
        with SMBus(1) as smbus:
            smbus.write_bytes(slave_address, bytearray(packed)) 
           #how would the slave know whether to write or receive? read_bytes for some reason isn't 
           #telling it to
            time.sleep(0.3)  # wait i2c process the request
            raw_list = list(smbus.read_bytes(slave_address, 5))  # the read_bytes contains the data 
           #either the slave is ignoring the read_bytes request from the pi or the pi never sends the 
           #request at all, so nothing happens between this comment and the last
           #read_bytes SHOULD be activating the WireSlave.onRequest() function of the esp32 slave
           #unless there is some other function i'm not aware of
           #format: first, length, data, crc8, end bytes
            print(raw_list)
            print("in smbus")

        # let's clean received data (this works fine and as expected, no problem here)
        #the only issue is that since the slave sends nothing back to the pi, the smbus reads either
        #junk that was already in the buffer, or nothing at all. I get junk like this: 
        #[177,255,255,255,255]
        unpacked = None
        with Unpacker() as unpacker:
            print("unpacker 1")
            unpacker.write(raw_list)
            print("unpacker 2")
            unpacked = unpacker.read()
            print("in unpacker")
        return unpacked

    except Exception as e:
        print("ERROR: {}".format(e))

write_from_rpi_to_esp32()
time.sleep(1)
read_from_rpi_to_esp32()

//Everything below this line is just for testing, just repeatedly requesting the esp32
//to send data back to the pi, which doesnt happen. Can be commented out
while(1):
    packed = None
    value = 69
    with Packer() as packer:
        packer.write(value)
        packer.end()
        packed = packer.read()
        print("in packer")
        
    raw_list = None
    with SMBus(1) as smbus:
        #smbus.write_bytes(slave_address, bytearray(packed)) #how would the slave know whether to write or receive?
        time.sleep(0.3)  # wait i2c process the request
        raw_list = list(smbus.read_bytes(slave_address, 5))  # the read_bytes contains the data format: first, length, data, crc8, end bytes
        rawList = smbus.read_byte(slave_address)
        print(rawList)
        print(raw_list)
        print("in smbus")
`

`#include <WireCrc.h>
#include <WirePacker.h>
#include <WireSlave.h>
#include <WireSlaveRequest.h>
#include <WireUnpacker.h>
#include "Arduino.h"
#include <Wire.h>

#define SDA_PIN 21
#define SCL_PIN 22
#define I2C_SLAVE_ADDR 0x08
#define Pi2ESP 34 //pin 26 on pi
#define ESP2Pi 32 //pin 6 on pi

bool espReady = 0;
bool received = false;

void receiveEvent(int howMany);
void requestEvent();

// LED on pin 13
const int ledPin = 4; 

void setup() {
  Serial.begin(115200);
  pinMode(Pi2ESP, INPUT); //pin that will tell us if pi is asking if we are ready
  pinMode(ESP2Pi, OUTPUT); //pin we will use to tell the pi we are reeady
  
 
  // Join I2C bus as slave with address 8
  bool success = WireSlave.begin(SDA_PIN, SCL_PIN, I2C_SLAVE_ADDR);
    if (!success) {
        Serial.println("I2C slave init failed");
        while(1) delay(100);
    }
  
  // Call receiveEvent when data received                
  WireSlave.onReceive(receiveEvent);
  // Call requestEvent when data requested
  WireSlave.onRequest(requestEvent);
}

void loop() {
  
  //check if pi is ready to send data to esp32
  /*if(digitalRead(Pi2ESP) == HIGH)
  {
    //then tell the pi that we are ready to start receiving signals by pulling our handshake pin //high
    digitalWrite(ESP2Pi, HIGH);
    espReady = 1;
    Serial.println("espReady");
    delay(100);
    digitalWrite(ESP2Pi, LOW);

    received = true;
  }

  if(received == true)
  {
    int b = WireSlave.read();
    received = false;
    Serial.println(b);
  }*/
 
  WireSlave.update();
  delay(1);
}


// Function that executes whenever data is received from master
void receiveEvent(int howMany) {
  while (WireSlave.available()) { // loop through all but the last
    int c = WireSlave.read(); // receive byte as a character
    Serial.println(c);
    digitalWrite(ESP2Pi, LOW);
    //just testing to see if i could get the esp32 to send bits anyways on either receiveEvent or 
    //requestEvent
    requestEvent();
  }
}

void requestEvent()
{
    static byte y = 100;
    Serial.println("data sent");
    WireSlave.print("y is ");
    WireSlave.write(y++);
    
}`

**Comment by DexterBurns** [comment]
Hey @MkLHX , I Didnt do too much changing of the example code, just switched around the slave_address variables and the register variables. The write_from_rpi_to_esp32() works fine for me. Alot of comments added where my concerns were. First block of code is what im running on my Pi3b+ and the next block is what i'm running on the esp32. The receiveEvent() function on the esp32 works with the write_from_rpi_to_esp32(). Apologies, for the text files, github would not work with me when i tried to insert the code directly into the comment
esp32i2cReceiver.txt is a python file
i2cPacker.txt is a c++ .ino file

[esp32i2cReceiver.txt](https://github.com/MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE/files/6331609/esp32i2cReceiver.txt)
[i2cPacker.txt](https://github.com/MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE/files/6331610/i2cPacker.txt)

**Comment by MkLHX** [comment]
@DexterBurns 
I think you're lost yourself in this test.

esp32i2cReceiver.txt is c++ file and i2cPacker.txt is python for raspberry pi side

_You can write code snippets by using insert code shortcut ctrl+e_

I haven't the time to debug your project. But code you used have to work.

I checked the profesional side code and it's the same as this repository.

You have to understand what is expected by esp32 driver side CRC8, packer and unpacker.

esp32 expected encoded data with this pattern first, length, data, crc8, end bytes in an byte array

that the role of packer class. the unpacker extract data from the same pattern from the esp32.

CRC8 class build the CRC8 from data you wan't send to the i2c slave from master (Here the RPI).

So for me the issue is on the ESP32 code side.


this a part of the c++ code from Platformio i ran inside esp32 slave side:

```
#include <Arduino.h>
#ifndef Wire
#include <Wire.h>
#endif
#ifndef WireSlave
#include <WireSlave.h>
#endif

void receiveEvent(int numBytes);
void requestEvent(void);

byte i2cAddr = 0x21 // or wathever
int howManyBytesReceived;
uint8_t registerCode;

void receiveEvent(int numBytes)
{

    Serial.print(F("---> recieved "));
    Serial.print(numBytes);
    howManyBytesReceived = numBytes;
    Serial.println(F(" events on i2c bus"));
    registerCode = WireSlave.read();
}

void requestEvent(void)
{
    Serial.print(F("---> request register value: "));
    Serial.print(registerCode, DEC);
    Serial.print(F(" / 0x0"));
    Serial.println(registerCode, HEX);
    
    // switch case for multiple i2c registers
    switch (registerCode)
    {
    case 0x00:
    {
        Serial.print("case of register 0x00");
        // return value about register 0x00 uint8_t format
        const uint8_t device_type = 0x00;
        WireSlave.write(device_type);
        break;
    }
    case 0x01:
    {
        Serial.print("case of register 0x01");
        // return value about register 0x01 uint8_t format
        const uint8_t device_firmware = 10; // send 10 divide by 10 to get the real value
        WireSlave.write(device_firmware);
        break;
    }
    default {
        Serial.print("UNKNOW REGISTER: ");
        Serial.println(registerCode);
    }
    }
}

void setup()
{
    Serial.begin(115200);
    bool ready = WireSlave.begin(I2C_SDA_PIN, I2C_SCL_PIN, i2cAddr);
    if (!ready)
    {
        Serial.println(F("I2C slave init failed"));
        while (true)
            delay(100);
    }
    WireSlave.onReceive(receiveEvent); // receive register value
    WireSlave.onRequest(requestEvent); // send register value
}

void loop()
{
    // your other logic than i2c here
    WireSlave.update();
    delay(5); // cadencing loop to allow other i2c device interrupt
}
```

**Comment by MkLHX** [comment]
@DexterBurns 

i've just push on master new examples snippets.

The esp32 slave side is tested on Platformio project not on Arduino .ino project

Please read about https://github.com/MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE#to-use-esp32-as-slave-on-i2c-bus-you-have-to-use-esp32_i2c_slave-c-library

**Comment by DexterBurns** [comment]
Ah okay, thanks for the updated example. I am trying this on platformio and still getting the same results unfortunately. I'll keep trying though to see if i can solve the issue.

Thanks,
-Dexter

**Comment by MkLHX** [comment]
@DexterBurns ok let me know if you find any solution

**Comment by MkLHX** [comment]
@DexterBurns look @ this https://github.com/gutierrezps/ESP32_I2C_Slave/issues/12

there is an issue with my library and the v0.3.0 of the ESP32 I2C SLAVE

you can use the v0.2.0 it works
