### ISSUE TITLE
Remote i/o Error

### ISSUE THREAD

**Issue by adnan6336** [MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE#3]
Hi there, I am trying to use your library and I am facing this error while connecting to esp32 dev kit.
"I/O Remote error"

I have verified that esp32 is on i2c on the address 0x04 using i2cdetect -y 1.
please let me know what am I doing wrong.

**Comment by MkLHX** [comment]
Hi @adnan6336 
Wich version of esp32 i2c you use?

Seem the last version the logic change and i haven't the time to update my lib logic to follow changes.

So please use esp32_i2c_slave v2.0 it works very well.

I have to put warning about this on readme.md

And put the link on v2.0 on it too.

**Comment by MkLHX** [comment]
see https://github.com/gutierrezps/ESP32_I2C_Slave/issues/12

**Comment by adnan6336** [comment]
hi @MkLHX 
I am now using v0.2.0 after seeing your reply.

error remains same.
My setup:

Rpi 4 connected with esp32 dev kit v1.
scl -- scl
sda -- sda
gnd -- gnd

when i run :
i2cdetect -y 1

I get this:

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- 21 -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         

I tested your program fro esp32 and now currently uploaded slave-receiver example from ESP32_I2C_Slave library.
i2c connection seems fine because it shows correct address "21"

when I run this in python:
rom Adafruit_PureIO.smbus import SMBus  # pip install adafruit-blinka
from Raspberry_Pi_Master_for_ESP32_I2C_SLAVE.packer import Packer
from Raspberry_Pi_Master_for_ESP32_I2C_SLAVE.unpacker import Unpacker
import time


slave_address = 0x21  # slave address is 4
register = 0x01  # register to write is 0x01
value = 0x01


def write_from_rpi_to_esp32():
    try:
        # change 1 of SMBus(1) to bus number on your RPI
        smbus = SMBus(1)
        # prepare the data
        packed = None
        with Packer() as packer:
            packer.write(register)
            packer.write(value)
            packer.end()
            packed = packer.read()
        smbus.write_bytes(register, bytearray(packed))
    except Exception as e:
        print("ERROR: {}".format(e))

write_from_rpi_to_esp32()

i get this:
ERROR: [Errno 121] Remote I/O error

please help. 
Thanks for your prompt response. much appreciated.

**Comment by adnan6336** [comment]
Update:
I have used the code of esp32 and python from this link "gutierrezps/ESP32_I2C_Slave#12"
and now its working I guess because output is like this:

I2c devices found:  [96]
Data to unpack:  244
packed:  [2, 5, 244, 21, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Data to unpack:  [2, 5, 127, 185, 4]
[127]

do let me know If I am wrong.

My ultimate objective is to send an integer(lets say 11) from RPI to slave esp32 and when esp32 recieve it, it concatenate with (lets say 5) and return to RPI where python print (11+5)
can you help me with that? if this works then I can do more with it for the actual goal.

**Comment by adnan6336** [comment]
Update:
so it seems like version v0.2.0 is working for me and I have successfully accomplished my goal that was to send some string from RPI to esp32 via i2c and get the response back with date concatenated in the actual message.
Input: helloworld
response: helloworld_01012021

Thanks.

**Comment by MkLHX** [comment]
Hi @adnan6336 
Sorry for late reply, I'm trying to sleep when sun is down 😁

Great to hear you manage to use it!

Just for better explanation:

You can use v0.0.6 or master of Raspberry pi python side lib with only the v0.0.2 of esp32 side c++ lib.

The latest esp32 side lib have some breaking changes about logic and i have to update the python lib allow use of it.

If it works on rpi4 that really great! I can add it on readme section 🤘
